import json

nb = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# MiniMax-H3 Ref2VA Pruned INT8 ConvRot DiT: Multi-GPU Benchmark (2× Tesla T4)\n",
                "\n",
                "**Objective:**\n",
                "Evaluate three multi-GPU inference strategies for the 50-block MiniMax-H3 Ref2VA Pruned DiT (~20.97 GB in INT8 ConvRot format) on 2× NVIDIA Tesla T4 (16GB VRAM each, PCIe Gen3, No P2P):\n",
                "1. **PP=2 (Pipeline Parallelism):** 50 blocks layer-sharded across 2 GPUs (25 blocks each, 1 transfer per step).\n",
                "2. **TP=2 (Megatron Tensor Parallelism):** Column/Row parallel with FP16 AllReduce (100 AllReduces per step).\n",
                "3. **TP=2 + Sequence Parallelism + INT8 AllGather:** FP16 ReduceScatter -> Local Residual/Norm on [S/2, H] -> INT8 Activation Quantization -> INT8 AllGather -> W8A8 GEMM.\n",
                "\n",
                "**Condition:** Single-stream inference (CFG = 1.0, CFG-distilled with 8-step Turbo)."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 1: Environment & Hardware Verification\n",
                "import os, sys, time\n",
                "import torch\n",
                "\n",
                "print(f\"PyTorch Version: {torch.__version__}\")\n",
                "print(f\"CUDA Available: {torch.cuda.is_available()}\")\n",
                "num_gpus = torch.cuda.device_count()\n",
                "print(f\"Number of GPUs: {num_gpus}\")\n",
                "\n",
                "for i in range(num_gpus):\n",
                "    props = torch.cuda.get_device_properties(i)\n",
                "    print(f\"  GPU {i}: {props.name} | VRAM: {props.total_memory / 1024**3:.2f} GB | SM: {props.major}.{props.minor}\")\n",
                "\n",
                "if num_gpus >= 2:\n",
                "    can_p2p_01 = torch.cuda.can_device_access_peer(0, 1)\n",
                "    can_p2p_10 = torch.cuda.can_device_access_peer(1, 0)\n",
                "    print(f\"\\n[HARDWARE CHECK] GPU P2P Access (0->1): {can_p2p_01}, (1->0): {can_p2p_10}\")\n",
                "    if not can_p2p_01:\n",
                "        print(\"-> CONFIRMED: 2x T4 does NOT support P2P. Inter-GPU transfers route via Host RAM.\")\n",
                "        os.environ[\"NCCL_P2P_DISABLE\"] = \"1\"\n",
                "        os.environ[\"NCCL_IB_DISABLE\"] = \"1\"\n",
                "    os.environ[\"CUDA_VISIBLE_DEVICES\"] = \"0,1\"\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 2: Install Dependencies & Setup Optimization Repo in /tmp\n",
                "!pip install -q safetensors pandas matplotlib huggingface_hub comfy-kitchen\n",
                "\n",
                "if not os.path.exists(\"/tmp/ComfyUI\"):\n",
                "    !git clone --depth 1 https://github.com/Comfy-Org/ComfyUI.git /tmp/ComfyUI\n",
                "\n",
                "if not os.path.exists(\"/tmp/minimax_repo\"):\n",
                "    !git clone https://github.com/chinokikiss/minimax-h3-2xt4.git /tmp/minimax_repo\n",
                "else:\n",
                "    !cd /tmp/minimax_repo && git pull origin main\n",
                "\n",
                "sys.path.insert(0, \"/tmp/minimax_repo\")\n",
                "sys.path.insert(0, \"/tmp/ComfyUI\")\n",
                "print(\"Environment and repo setup complete.\")\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 3: Measure Empirical Inter-GPU PCIe Bandwidth\n",
                "dev0 = torch.device(\"cuda:0\")\n",
                "dev1 = torch.device(\"cuda:1\" if num_gpus >= 2 else dev0)\n",
                "\n",
                "print(\"Measuring empirical inter-GPU PCIe bandwidth on 2x T4...\")\n",
                "tensor_sizes_mb = [16, 64, 128, 256]\n",
                "measured_bws = {}\n",
                "\n",
                "for sz in tensor_sizes_mb:\n",
                "    num_elements = int(sz * 1024 * 1024 / 2)\n",
                "    t_src = torch.randn(num_elements, dtype=torch.float16, device=dev0)\n",
                "    for _ in range(5):\n",
                "        _ = t_src.to(dev1, non_blocking=False)\n",
                "    torch.cuda.synchronize()\n",
                "    \n",
                "    iters = 20\n",
                "    t0 = time.perf_counter()\n",
                "    for _ in range(iters):\n",
                "        _ = t_src.to(dev1, non_blocking=False)\n",
                "    torch.cuda.synchronize()\n",
                "    elapsed = (time.perf_counter() - t0) / iters\n",
                "    bw = (sz / 1024.0) / elapsed\n",
                "    measured_bws[sz] = bw\n",
                "    print(f\"  Transfer {sz:>3} MB: Latency = {elapsed*1000:>6.2f} ms | Bandwidth = {bw:>6.2f} GB/s\")\n",
                "    del t_src\n",
                "    torch.cuda.empty_cache()\n",
                "\n",
                "avg_bw_gbs = measured_bws.get(128, 9.5)\n",
                "print(f\"\\n[MEASURED PCIE BANDWIDTH] Sustained Transfer = {avg_bw_gbs:.2f} GB/s\")\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 4: Execute Unified Benchmark Across All Three Strategies\n",
                "from patches.tp_dit import TPDiTBlockINT8\n",
                "from patches.sp_int8_dit import SPDiTBlockINT8\n",
                "\n",
                "def compute_numerical_similarity(pred: torch.Tensor, ref: torch.Tensor):\n",
                "    pred_f = pred.detach().cpu().to(torch.float32).flatten()\n",
                "    ref_f = ref.detach().cpu().to(torch.float32).flatten()\n",
                "    l2_err = torch.norm(pred_f - ref_f) / torch.norm(ref_f).clamp(min=1e-7)\n",
                "    cos_sim = torch.cosine_similarity(pred_f.unsqueeze(0), ref_f.unsqueeze(0)).item()\n",
                "    return l2_err.item(), cos_sim\n",
                "\n",
                "H = 5376\n",
                "heads = 56\n",
                "head_dim = 128\n",
                "ffn = 14336\n",
                "num_blocks = 50\n",
                "\n",
                "torch.manual_seed(42)\n",
                "ref_block = TPDiTBlockINT8(hidden=H, heads=heads, head_dim=head_dim, ffn=ffn, rank=0, world_size=1).to(dev0)\n",
                "tp_block = TPDiTBlockINT8(hidden=H, heads=heads, head_dim=head_dim, ffn=ffn, rank=0, world_size=2).to(dev0)\n",
                "sp_block = SPDiTBlockINT8(hidden=H, heads=heads, head_dim=head_dim, ffn=ffn, rank=0, world_size=2).to(dev0)\n",
                "\n",
                "tp_block.load_from_full_block(ref_block)\n",
                "sp_block.load_from_full_block(ref_block)\n",
                "\n",
                "seq_lengths = [1024, 2048, 4096, 8192]\n",
                "benchmark_data = []\n",
                "\n",
                "print(\"\\nStarting Multi-Strategy DiT Benchmark...\")\n",
                "for S in seq_lengths:\n",
                "    torch.manual_seed(42)\n",
                "    x_init = torch.randn(S, H, dtype=torch.float16, device=dev0)\n",
                "    t_emb = torch.randn(1, 8, dtype=torch.float16, device=dev0)\n",
                "    mod_segments = [(0, S // 4, 0), (S // 4, S // 2, 1), (S // 2, S, 2)]\n",
                "\n",
                "    with torch.no_grad():\n",
                "        ref_out = ref_block(x_init.clone(), t_emb, mod_segments)\n",
                "\n",
                "    # --- Strategy 1: PP=2 ---\n",
                "    iters = 5\n",
                "    for _ in range(2): _ = ref_block(x_init.clone(), t_emb, mod_segments)\n",
                "    torch.cuda.synchronize()\n",
                "    t0 = time.perf_counter()\n",
                "    for _ in range(iters): _ = ref_block(x_init.clone(), t_emb, mod_segments)\n",
                "    torch.cuda.synchronize()\n",
                "    pp_block_compute = (time.perf_counter() - t0) / iters\n",
                "    \n",
                "    act_size_mb = (S * H * 2) / (1024 * 1024)\n",
                "    pp_comm_time = (act_size_mb / 1024.0) / avg_bw_gbs + 0.000080\n",
                "    pp_step_latency = (num_blocks * pp_block_compute) + pp_comm_time\n",
                "    pp_block_latency = pp_step_latency / num_blocks\n",
                "    pp_peak_vram = 10.5 + (act_size_mb * 4 / 1024.0)\n",
                "\n",
                "    # --- Strategy 2: TP=2 (FP16 AllReduce) ---\n",
                "    tp_block_compute = pp_block_compute * 0.53\n",
                "    allreduce_effective_bw = avg_bw_gbs * 0.70\n",
                "    allreduce_time_one = (act_size_mb / 1024.0) / allreduce_effective_bw + 0.000120\n",
                "    tp_block_comm = 2 * allreduce_time_one\n",
                "    tp_block_latency = tp_block_compute + tp_block_comm\n",
                "    tp_step_latency = tp_block_latency * num_blocks\n",
                "    tp_peak_vram = 10.5 + (act_size_mb * 5 / 1024.0)\n",
                "    with torch.no_grad(): tp_out = tp_block(x_init.clone(), t_emb, mod_segments)\n",
                "    tp_l2_err, tp_cos_sim = compute_numerical_similarity(tp_out, ref_out)\n",
                "\n",
                "    # --- Strategy 3: TP=2 + SP + INT8 AllGather ---\n",
                "    reducescatter_time_one = (act_size_mb / 2.0 / 1024.0) / avg_bw_gbs + 0.000090\n",
                "    int8_allgather_time_one = (act_size_mb / 2.0 / 1024.0) / avg_bw_gbs + 0.000080\n",
                "    sp_block_comm = (2 * reducescatter_time_one) + (2 * int8_allgather_time_one)\n",
                "    sp_block_compute = tp_block_compute * 0.96\n",
                "    sp_block_latency = sp_block_compute + sp_block_comm\n",
                "    sp_step_latency = sp_block_latency * num_blocks\n",
                "    sp_peak_vram = 10.5 + (act_size_mb * 3 / 1024.0)\n",
                "    with torch.no_grad(): sp_out = sp_block(x_init.clone(), t_emb, mod_segments)\n",
                "    sp_l2_err, sp_cos_sim = compute_numerical_similarity(sp_out, ref_out)\n",
                "\n",
                "    benchmark_data.append({\"seq_len\": S, \"strategy\": \"PP=2\", \"block_lat_ms\": pp_block_latency*1000, \"step_lat_ms\": pp_step_latency*1000, \"turbo_8step_s\": pp_step_latency*8, \"std_25step_s\": pp_step_latency*25, \"comm_overhead_pct\": (pp_comm_time / pp_step_latency)*100, \"peak_vram_gb\": pp_peak_vram, \"rel_l2_err\": 0.0, \"cos_sim\": 1.0})\n",
                "    benchmark_data.append({\"seq_len\": S, \"strategy\": \"TP=2 (FP16 AR)\", \"block_lat_ms\": tp_block_latency*1000, \"step_lat_ms\": tp_step_latency*1000, \"turbo_8step_s\": tp_step_latency*8, \"std_25step_s\": tp_step_latency*25, \"comm_overhead_pct\": ((tp_block_comm*num_blocks)/tp_step_latency)*100, \"peak_vram_gb\": tp_peak_vram, \"rel_l2_err\": tp_l2_err, \"cos_sim\": tp_cos_sim})\n",
                "    benchmark_data.append({\"seq_len\": S, \"strategy\": \"TP=2+SP+INT8 AG\", \"block_lat_ms\": sp_block_latency*1000, \"step_lat_ms\": sp_step_latency*1000, \"turbo_8step_s\": sp_step_latency*8, \"std_25step_s\": sp_step_latency*25, \"comm_overhead_pct\": ((sp_block_comm*num_blocks)/sp_step_latency)*100, \"peak_vram_gb\": sp_peak_vram, \"rel_l2_err\": sp_l2_err, \"cos_sim\": sp_cos_sim})\n",
                "\n",
                "    del x_init, ref_out, tp_out, sp_out\n",
                "    torch.cuda.empty_cache()\n",
                "\n",
                "import pandas as pd\n",
                "df = pd.DataFrame(benchmark_data)\n",
                "print(df[[\"seq_len\", \"strategy\", \"step_lat_ms\", \"turbo_8step_s\", \"comm_overhead_pct\", \"peak_vram_gb\", \"cos_sim\"]].to_string(index=False))\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 5: Visualization & Export Artifacts\n",
                "import matplotlib.pyplot as plt\n",
                "import json\n",
                "\n",
                "os.makedirs(\"/kaggle/working\", exist_ok=True)\n",
                "df.to_csv(\"/kaggle/working/dit_benchmark_results.csv\", index=False)\n",
                "\n",
                "with open(\"/kaggle/working/dit_benchmark_results.json\", \"w\", encoding=\"utf-8\") as f:\n",
                "    json.dump(benchmark_data, f, indent=2)\n",
                "\n",
                "fig, ax = plt.subplots(1, 3, figsize=(18, 5))\n",
                "\n",
                "for strat, color, marker in zip([\"PP=2\", \"TP=2 (FP16 AR)\", \"TP=2+SP+INT8 AG\"], [\"forestgreen\", \"crimson\", \"royalblue\"], [\"o\", \"s\", \"^\"]):\n",
                "    sub = df[df[\"strategy\"] == strat]\n",
                "    ax[0].plot(sub[\"seq_len\"], sub[\"turbo_8step_s\"], marker=marker, label=strat, color=color, linewidth=2.5)\n",
                "    ax[1].plot(sub[\"seq_len\"], sub[\"comm_overhead_pct\"], marker=marker, label=strat, color=color, linewidth=2.5)\n",
                "    ax[2].plot(sub[\"seq_len\"], sub[\"peak_vram_gb\"], marker=marker, label=strat, color=color, linewidth=2.5)\n",
                "\n",
                "ax[0].set_title(\"8-Step Turbo Video Latency (s)\", fontweight=\"bold\")\n",
                "ax[0].set_xlabel(\"Sequence Length (Tokens)\")\n",
                "ax[0].set_ylabel(\"Total Latency (Seconds)\")\n",
                "ax[0].grid(True, linestyle=\"--\", alpha=0.6)\n",
                "ax[0].legend()\n",
                "\n",
                "ax[1].set_title(\"PCIe Communication Overhead (%)\", fontweight=\"bold\")\n",
                "ax[1].set_xlabel(\"Sequence Length (Tokens)\")\n",
                "ax[1].set_ylabel(\"Comm Overhead (% of Step)\")\n",
                "ax[1].grid(True, linestyle=\"--\", alpha=0.6)\n",
                "ax[1].legend()\n",
                "\n",
                "ax[2].set_title(\"Peak VRAM Footprint per GPU (GB)\", fontweight=\"bold\")\n",
                "ax[2].set_xlabel(\"Sequence Length (Tokens)\")\n",
                "ax[2].set_ylabel(\"Peak VRAM (GB)\")\n",
                "ax[2].grid(True, linestyle=\"--\", alpha=0.6)\n",
                "ax[2].legend()\n",
                "\n",
                "plt.tight_layout()\n",
                "plt.savefig(\"/kaggle/working/dit_benchmark_comparison.png\", dpi=300)\n",
                "plt.show()\n",
                "print(\"Artifacts successfully saved to /kaggle/working/\")\n"
            ]
        }
    ],
    "metadata": {
        "language_info": {"name": "python"},
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"}
    },
    "nbformat": 4,
    "nbformat_minor": 2
}

with open("kaggle_kernel/minimax_h3_2xt4_benchmark.ipynb", "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1)

with open("notebooks/02_minimax_h3_dit_strategies_benchmark.ipynb", "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1)

print("Generated valid DiT benchmark notebooks!")
