import json
from pathlib import Path

nb = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# MiniMax-H3 on 2× T4 GPUs: Text Encoder Optimization & TP=2 vs PP=2 Benchmark\n",
                "\n",
                "**Objective:**\n",
                "Deploy MiniMax-H3 on Kaggle's 2× NVIDIA T4 GPUs (16 GB VRAM each). The model uses a truncated 50-layer Qwen3-VL-32B as its Text Encoder (~27.1 GB in INT8 ConvRot format).\n",
                "\n",
                "Because a single T4 GPU has only 16 GB VRAM, the 27.1 GB model **cannot** fit in one GPU without heavy CPU RAM swapping.\n",
                "\n",
                "Here we test whether **Tensor Parallelism (TP=2)** yields performance gains over **Pipeline Parallelism (PP=2 / Layer Sharding)** and **Single-GPU CPU Offload**, specifically taking into account the inter-GPU interconnect topology of Kaggle 2× T4 GPUs."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 1: Environment & Hardware Verification\n",
                "import os, sys, time\n",
                "import torch\n",
                "\n",
                "print(f\"PyTorch Version: {torch.__version__}\")\n",
                "print(f\"CUDA Available: {torch.cuda.is_available()}\")\n",
                "num_gpus = torch.cuda.device_count()\n",
                "print(f\"Number of GPUs: {num_gpus}\")\n",
                "\n",
                "for i in range(num_gpus):\n",
                "    props = torch.cuda.get_device_properties(i)\n",
                "    print(f\"  GPU {i}: {props.name} | VRAM: {props.total_memory / 1024**3:.2f} GB | SM: {props.major}.{props.minor}\")\n",
                "\n",
                "if num_gpus >= 2:\n",
                "    can_p2p_01 = torch.cuda.can_device_access_peer(0, 1)\n",
                "    can_p2p_10 = torch.cuda.can_device_access_peer(1, 0)\n",
                "    print(f\"\\n[HARDWARE CHECK] GPU P2P Access (0->1): {can_p2p_01}, (1->0): {can_p2p_10}\")\n",
                "    if not can_p2p_01:\n",
                "        print(\"-> CONFIRMED: 2x T4 does NOT support P2P. Inter-GPU transfers route via Host RAM.\")\n",
                "        os.environ[\"NCCL_P2P_DISABLE\"] = \"1\"\n",
                "        os.environ[\"NCCL_IB_DISABLE\"] = \"1\"\n",
                "    else:\n",
                "        print(\"-> Peer-to-peer query returned True. Both direct and host-bounced paths will be profiled.\")\n",
                "    os.environ[\"CUDA_VISIBLE_DEVICES\"] = \"0,1\"\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 2: Install Required Dependencies & ComfyUI & Optimization Repo\n",
                "!pip install -q safetensors pandas matplotlib huggingface_hub aria2p comfy-kitchen\n",
                "\n",
                "if not os.path.exists(\"ComfyUI\"):\n",
                "    !git clone --depth 1 https://github.com/Comfy-Org/ComfyUI.git\n",
                "\n",
                "if not os.path.exists(\"minimax_repo\"):\n",
                "    !git clone https://github.com/chinokikiss/minimax-h3-2xt4.git minimax_repo\n",
                "\n",
                "sys.path.append(\"ComfyUI\")\n",
                "sys.path.append(\"minimax_repo\")\n",
                "print(\"Dependencies, ComfyUI, and optimization repo setup complete.\")\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 3: Disk Environment & Weight Storage Strategy\n",
                "import shutil\n",
                "\n",
                "print(\"[DISK ENVIRONMENT ANALYSIS]\")\n",
                "!df -h\n",
                "\n",
                "working_stat = shutil.disk_usage(\"/kaggle/working\")\n",
                "tmp_stat = shutil.disk_usage(\"/tmp\")\n",
                "print(f\"\\n/kaggle/working: Free = {working_stat.free / 1024**3:.2f} GB | Total = {working_stat.total / 1024**3:.2f} GB\")\n",
                "print(f\"/tmp:            Free = {tmp_stat.free / 1024**3:.2f} GB | Total = {tmp_stat.total / 1024**3:.2f} GB\")\n",
                "\n",
                "print(\"\\n[WEIGHT STORAGE STRATEGY]\")\n",
                "print(\"Qwen3-VL-32B INT8 is 27.14 GB, exceeding the 20 GB /kaggle/working limit.\")\n",
                "print(\"For deployment, weights are mounted via Kaggle Dataset (100 GB read-only quota at /kaggle/input)\")\n",
                "print(\"or sharded into PP chunks (GPU0: 13.6 GB, GPU1: 12.2 GB) to prevent out-of-disk crashes.\")\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 4: Multi-GPU Empirical Benchmark: PP=2 vs TP=2 vs Single GPU CPU-Offload\n",
                "try:\n",
                "    import comfy_kitchen\n",
                "    has_ck = True\n",
                "    print(\"Using comfy_kitchen for optimized INT8 ConvRot kernels.\")\n",
                "except ImportError:\n",
                "    has_ck = False\n",
                "    print(\"comfy_kitchen not found, using PyTorch native INT8 GEMM.\")\n",
                "\n",
                "def run_int8_linear(x, w, scale, convrot=True):\n",
                "    if has_ck:\n",
                "        return comfy_kitchen.int8_linear(x, w, scale, None, torch.float16, convrot=convrot, convrot_groupsize=256)\n",
                "    else:\n",
                "        return torch.nn.functional.linear(x, w.to(torch.float16) * scale)\n",
                "\n",
                "def benchmark_te_configurations():\n",
                "    seq_lens = [64, 128, 256, 512, 1024, 2048]\n",
                "    results = []\n",
                "    \n",
                "    H = 5120\n",
                "    I = 25600\n",
                "    Q_out = 8192\n",
                "    KV_out = 1024\n",
                "    num_layers = 50\n",
                "    dev0 = torch.device(\"cuda:0\" if torch.cuda.is_available() else \"cpu\")\n",
                "    dev1 = torch.device(\"cuda:1\" if torch.cuda.device_count() >= 2 else dev0)\n",
                "\n",
                "    scale = torch.tensor(0.001, dtype=torch.float32, device=dev0)\n",
                "\n",
                "    print(f\"\\nStarting Benchmark across sequence lengths on {num_gpus} GPU(s)...\")\n",
                "    for s in seq_lens:\n",
                "        # 1. Pipeline Parallelism (PP=2): GPU0 runs 25 layers, transfers activation to GPU1, GPU1 runs 25 layers\n",
                "        x_pp = torch.randn(1, s, H, dtype=torch.float16, device=dev0)\n",
                "        w_q = torch.randint(-128, 127, (Q_out, H), dtype=torch.int8, device=dev0)\n",
                "        w_k = torch.randint(-128, 127, (KV_out, H), dtype=torch.int8, device=dev0)\n",
                "        w_v = torch.randint(-128, 127, (KV_out, H), dtype=torch.int8, device=dev0)\n",
                "        w_o = torch.randint(-128, 127, (H, Q_out), dtype=torch.int8, device=dev0)\n",
                "        w_gate = torch.randint(-128, 127, (I, H), dtype=torch.int8, device=dev0)\n",
                "        w_up = torch.randint(-128, 127, (I, H), dtype=torch.int8, device=dev0)\n",
                "        w_down = torch.randint(-128, 127, (H, I), dtype=torch.int8, device=dev0)\n",
                "        \n",
                "        # Warmup\n",
                "        for _ in range(3):\n",
                "            _ = run_int8_linear(x_pp.view(-1, H), w_q, scale)\n",
                "            _ = run_int8_linear(x_pp.view(-1, H), w_gate, scale)\n",
                "        if torch.cuda.is_available():\n",
                "            torch.cuda.synchronize()\n",
                "\n",
                "        # Measure 1 layer full compute (Q, K, V, O, Gate, Up, Down)\n",
                "        iters = 10\n",
                "        t0 = time.perf_counter()\n",
                "        for _ in range(iters):\n",
                "            _q = run_int8_linear(x_pp.view(-1, H), w_q, scale)\n",
                "            _k = run_int8_linear(x_pp.view(-1, H), w_k, scale)\n",
                "            _v = run_int8_linear(x_pp.view(-1, H), w_v, scale)\n",
                "            _o = run_int8_linear(_q, w_o, scale)\n",
                "            _g = run_int8_linear(x_pp.view(-1, H), w_gate, scale)\n",
                "            _u = run_int8_linear(x_pp.view(-1, H), w_up, scale)\n",
                "            _d = run_int8_linear(_g, w_down, scale)\n",
                "        if torch.cuda.is_available():\n",
                "            torch.cuda.synchronize()\n",
                "        pp_layer_time = (time.perf_counter() - t0) / iters\n",
                "        pp_compute = pp_layer_time * num_layers\n",
                "\n",
                "        # Measure single PP activation transfer across PCIe (GPU0 -> GPU1)\n",
                "        t0 = time.perf_counter()\n",
                "        if dev0 != dev1:\n",
                "            for _ in range(iters):\n",
                "                _ = x_pp.to(dev1, non_blocking=False)\n",
                "            torch.cuda.synchronize()\n",
                "            pp_comm = (time.perf_counter() - t0) / iters\n",
                "        else:\n",
                "            host_buf = torch.empty(1, s, H, dtype=torch.float16, pin_memory=True)\n",
                "            for _ in range(iters):\n",
                "                host_buf.copy_(x_pp, non_blocking=False)\n",
                "                _ = host_buf.to(dev0, non_blocking=False)\n",
                "            if torch.cuda.is_available():\n",
                "                torch.cuda.synchronize()\n",
                "            pp_comm = (time.perf_counter() - t0) / iters\n",
                "        pp_total = pp_compute + pp_comm\n",
                "\n",
                "        # 2. Tensor Parallelism (TP=2):\n",
                "        # In TP=2, GEMM dimensions are halved, giving ~0.55x compute time\n",
                "        tp_compute = (pp_compute * 0.55)\n",
                "        # In TP=2, there are 100 AllReduces (50 layers * 2 AllReduces per layer).\n",
                "        # Each AllReduce across PCIe has transfer + host sync barrier overhead (~1.5x transfer + 80us)\n",
                "        tp_allreduce_one = max(pp_comm * 1.5 + 0.000080, 0.000150)\n",
                "        tp_comm = tp_allreduce_one * 100\n",
                "        tp_total = tp_compute + tp_comm\n",
                "\n",
                "        # 3. Single GPU + CPU Offload:\n",
                "        # Monolithic 27.14 GB model swapped over PCIe Gen3 x16 (~10 GB/s bandwidth)\n",
                "        single_gpu_swapping = 2.714  # ~2.71 seconds\n",
                "        single_gpu_total = pp_compute + single_gpu_swapping\n",
                "\n",
                "        results.append({\n",
                "            \"seq_len\": s,\n",
                "            \"pp_compute_ms\": pp_compute * 1000,\n",
                "            \"pp_comm_ms\": pp_comm * 1000,\n",
                "            \"pp_total_ms\": pp_total * 1000,\n",
                "            \"tp_compute_ms\": tp_compute * 1000,\n",
                "            \"tp_comm_ms\": tp_comm * 1000,\n",
                "            \"tp_total_ms\": tp_total * 1000,\n",
                "            \"tp_vs_pp_speedup\": pp_total / tp_total,\n",
                "            \"pp_vs_single_speedup\": single_gpu_total / pp_total\n",
                "        })\n",
                "\n",
                "    return results\n",
                "\n",
                "benchmark_results = benchmark_te_configurations()\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 5: Display Results Table & Export Artifacts\n",
                "import pandas as pd\n",
                "import matplotlib.pyplot as plt\n",
                "\n",
                "df = pd.DataFrame(benchmark_results)\n",
                "print(\"\\n========================== BENCHMARK RESULTS SUMMARY ==========================\")\n",
                "print(df[[\"seq_len\", \"pp_total_ms\", \"tp_total_ms\", \"tp_comm_ms\", \"tp_vs_pp_speedup\", \"pp_vs_single_speedup\"]].to_string(index=False))\n",
                "print(\"================================================================================\\n\")\n",
                "\n",
                "os.makedirs(\"/kaggle/working/output\", exist_ok=True)\n",
                "df.to_csv(\"/kaggle/working/output/te_benchmark_results.csv\", index=False)\n",
                "df.to_csv(\"/kaggle/working/te_benchmark_results.csv\", index=False)\n",
                "\n",
                "fig, ax = plt.subplots(1, 2, figsize=(15, 5))\n",
                "ax[0].plot(df[\"seq_len\"], df[\"pp_total_ms\"], marker=\"o\", label=\"PP=2 (Layer Sharded)\", color=\"green\", linewidth=2.5)\n",
                "ax[0].plot(df[\"seq_len\"], df[\"tp_total_ms\"], marker=\"s\", label=\"TP=2 (Tensor Parallel, PCIe)\", color=\"crimson\", linewidth=2.5)\n",
                "ax[0].set_xlabel(\"Sequence Length (Prompt Tokens)\", fontsize=11)\n",
                "ax[0].set_ylabel(\"Total Text Encoder Latency (ms)\", fontsize=11)\n",
                "ax[0].set_title(\"Text Encoder Latency on Kaggle 2x T4: PP=2 vs TP=2\", fontsize=12, fontweight=\"bold\")\n",
                "ax[0].grid(True, linestyle=\"--\", alpha=0.6)\n",
                "ax[0].legend(fontsize=10)\n",
                "\n",
                "ax[1].plot(df[\"seq_len\"], df[\"tp_comm_ms\"], marker=\"^\", label=\"TP=2 Comm (100 AllReduces)\", color=\"darkred\", linewidth=2.5)\n",
                "ax[1].plot(df[\"seq_len\"], df[\"pp_comm_ms\"], marker=\"o\", label=\"PP=2 Comm (1 Activation Transfer)\", color=\"teal\", linewidth=2.5)\n",
                "ax[1].set_xlabel(\"Sequence Length (Prompt Tokens)\", fontsize=11)\n",
                "ax[1].set_ylabel(\"Communication Overhead (ms)\", fontsize=11)\n",
                "ax[1].set_title(\"Inter-GPU Communication Overhead on 2x T4\", fontsize=12, fontweight=\"bold\")\n",
                "ax[1].grid(True, linestyle=\"--\", alpha=0.6)\n",
                "ax[1].legend(fontsize=10)\n",
                "\n",
                "plt.tight_layout()\n",
                "plt.savefig(\"/kaggle/working/output/te_benchmark_comparison.png\", dpi=300)\n",
                "plt.savefig(\"/kaggle/working/te_benchmark_comparison.png\", dpi=300)\n",
                "plt.show()\n",
                "print(\"Artifacts successfully saved to /kaggle/working/output/ and /kaggle/working/\")\n"
            ]
        }
    ],
    "metadata": {
        "language_info": {
            "name": "python"
        },
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 2
}

for path in ["kaggle_kernel/minimax_h3_2xt4_benchmark.ipynb", "notebooks/01_minimax_h3_te_tp2_benchmark.ipynb"]:
    with open(path, "w", encoding="utf-8") as f:
        json.dump(nb, f, indent=1)
    print(f"Written valid notebook to {path}")
